[package]
name = "pika3"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4.1"
im = "15.1.0"
im-rope = "*"
lsp-server = "0.7.7"
lsp-types = "0.95.1"
serde = "1.0.210"
serde_json = "1.0.128"
tap = "1.0.1"
yansi = "*"
